CALL %~dp0.\ffmpeg.settings.cmd

if "%FFMPEG_INPUT_FILE_AUDIO%"=="" if /I "%~x1"==".wav" SET FFMPEG_INPUT_FILE_AUDIO=%~1
if "%FFMPEG_INPUT_FILE_AUDIO%"=="" if /I "%~x2"==".wav" SET FFMPEG_INPUT_FILE_AUDIO=%~2

if "%FFMPEG_INPUT_FILE_AUDIO%"=="" if /I "%~x1"==".m4a" SET FFMPEG_INPUT_FILE_AUDIO=%~1
if "%FFMPEG_INPUT_FILE_AUDIO%"=="" if /I "%~x2"==".m4a" SET FFMPEG_INPUT_FILE_AUDIO=%~2

if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x1"==".avi" SET FFMPEG_INPUT_FILE_VIDEO=%~1
if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x2"==".avi" SET FFMPEG_INPUT_FILE_VIDEO=%~2

if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x1"==".mpg" SET FFMPEG_INPUT_FILE_VIDEO=%~1
if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x2"==".mpg" SET FFMPEG_INPUT_FILE_VIDEO=%~2

if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x1"==".mpeg" SET FFMPEG_INPUT_FILE_VIDEO=%~1
if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x2"==".mpeg" SET FFMPEG_INPUT_FILE_VIDEO=%~2

if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x1"==".mp4" SET FFMPEG_INPUT_FILE_VIDEO=%~1
if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x2"==".mp4" SET FFMPEG_INPUT_FILE_VIDEO=%~2

if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x1"==".m4v" SET FFMPEG_INPUT_FILE_VIDEO=%~1
if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x2"==".m4v" SET FFMPEG_INPUT_FILE_VIDEO=%~2

if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x1"==".mkv" SET FFMPEG_INPUT_FILE_VIDEO=%~1
if "%FFMPEG_INPUT_FILE_VIDEO%"=="" if /I "%~x2"==".mkv" SET FFMPEG_INPUT_FILE_VIDEO=%~2

for %%i in ("%FFMPEG_INPUT_FILE_VIDEO%") do (
  SET FFMPEG_INPUT_FILE_VIDEO_BASE=%%~dpni
  SET FFMPEG_INPUT_FILE_VIDEO_EXT=%%~xi
)

if "%FFMPEG_OUTPUT_FILE%"=="" SET FFMPEG_OUTPUT_FILE=%FFMPEG_INPUT_FILE_VIDEO_BASE%.merged%FFMPEG_INPUT_FILE_VIDEO_EXT%

"%FFMPEG_EXE%" ^
  -i "%FFMPEG_INPUT_FILE_VIDEO%" ^
  -i "%FFMPEG_INPUT_FILE_AUDIO%" ^
  -vcodec copy ^
  -acodec copy ^
  -map 0:v:0 -map 1:a:0 ^
  "%FFMPEG_OUTPUT_FILE%"
  
if "%SCRIPT_MODE%"=="" pause